name: "Docker Image Artifact Upload"
description: "Uploads docker image artifact for use across jobs in same workflow"
inputs:
  image:
    description: Docker image to upload
    required: true
  retention_days:
    description: Retention days for the image artifact
    required: false
    default: "0"
outputs:
  artifact_name:
    description: Name of artifact created in the process
runs:
  using: "node16"
  main: "dist/index.js"
